name: Pipeline_Operacao_CI

on:
  push:
    branches: ["main"]

jobs:

  web-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Baixando código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências WEB
        run: |
          pip install selenium webdriver-manager python-dotenv

      - name: Rodar testes WEB
        env:
          SAUCE_USERNAME: standard_user
          SAUCE_PASSWORD: secret_sauce
          SAUCE_URL: https://www.saucedemo.com/
        run: |
          cd tests-web
          PYTHONPATH=$(pwd) python -m test.test


  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Baixando código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar Newman
        run: npm install -g newman

      - name: Rodar testes API
        run: |
          cd tests-api
          newman run teste-petstore.json \
          --env-var "petId=241205" \
          --env-var "username=cassy_test"